using MediatR;

namespace RESQ.Application.UseCases.SystemConfig.Queries.GetMissionTeamReportDashboardSummary;

public record GetMissionTeamReportDashboardSummaryQuery : IRequest<MissionTeamReportDashboardSummaryResponse>;
