namespace RESQ.Domain.Enum.Identity;

public enum DocumentFileType
{
    WATER_SAFETY_CERT,
    WATER_RESCUE_CERT,
    TECHNICAL_RESCUE_CERT,
    DISASTER_RESPONSE_CERT,
    BASIC_MEDICAL_CERT,
    ADVANCED_MEDICAL_LICENSE,
    LAND_VEHICLE_LICENSE,
    WATER_VEHICLE_LICENSE,
    OTHER
}
